const QUEUE_NAME = "order_events";

const EVENTS = {
  ORDER_PLACED: "ORDER_PLACED",
  ORDER_READY: "ORDER_READY",
  ORDER_CANCELLED: "ORDER_CANCELLED"
};

const ORDER_STATUS = {
  PLACED: "PLACED",
  READY: "READY",
  COLLECTED: "COLLECTED",
  CANCELLED: "CANCELLED"
};

module.exports = {
  QUEUE_NAME,
  EVENTS,
  ORDER_STATUS
};